af83/chouette-core

- app/assets/stylesheets/components/_forms.sass
- app/assets/stylesheets/modules/_vj_collection.sass
- app/controllers/referential_vehicle_journeys_controller.rb
- app/helpers/vehicle_journeys_helper.rb
- app/models/chouette/route.rb
- app/services/referential_consolidated.rb
- app/views/referential_vehicle_journeys/_consolidated.html.slim
- app/views/referential_vehicle_journeys/_consolidated_line.html.slim
- app/views/referential_vehicle_journeys/_filters.html.slim
- app/views/referential_vehicle_journeys/_list.html.slim
- app/views/referential_vehicle_journeys/index.html.slim
:warning: Penser à ajouter la feature `consolidated_offers`
> 6923 consolidated offer

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
Refs #6974
Refs #6975
Refs #6976
> Updates dependencies with potential security breaches

- app/services/route_way_cost_calculator.rb
- lib/tom_tom/errors.rb
- lib/tom_tom/errors/matrix_remote_error.rb
- lib/tom_tom/matrix.rb
- lib/tom_tom/matrix/remote_error.rb
- spec/lib/tom_tom/matrix_spec.rb
- spec/services/route_way_cost_calculator_spec.rb
Améliore la gestion d'erreurs de TomTom. Ici, on ajoute un message de log quand TomTom répond avec une erreur.
> 6884 tomtom matrix  handle error when response doesn,t inclu

- app/assets/stylesheets/modules/_vj_collection.sass
- app/views/referential_vehicle_journeys/_consolidated.html.slim
- app/views/referential_vehicle_journeys/_consolidated_line.html.slim
> 6972 Fix consolidated view when togglable elements are open

- app/javascript/helpers/polyfills.js
- app/javascript/vehicle_journeys/components/tools/select2s/MissionSelect2.js
- package.json
- yarn.lock
> Refs #6845; Fix IE 

- app/models/simple_importer.rb
- app/models/simple_interface.rb
- app/models/simple_interfaces_group.rb
- lib/tasks/exports.rake
> 6216 Uniformize output folders

- app/assets/stylesheets/modules/_vj_collection.sass
- app/controllers/referential_vehicle_journeys_controller.rb
- app/models/chouette/route.rb
- app/models/chouette/stop_point.rb
- app/models/chouette/vehicle_journey.rb
- app/models/chouette/vehicle_journey_at_stop.rb
- app/services/referential_consolidated.rb
- app/views/referential_vehicle_journeys/_consolidated_line.html.slim
And improvements on the SQL queries
> 7031 Css fixes on Consolidated view

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_forms.sass
- app/assets/stylesheets/components/_lists.sass
- app/models/custom_field.rb
- app/uploaders/custom_field_attachment_uploader.rb
- app/views/shared/custom_fields/_attachment.html.slim
- spec/models/custom_field_spec.rb
- Show validation errors on fields
- Smarter attachments
> 6092 CustomlFields attachments

- app/javascript/helpers/CustomFieldsInputs.js
- app/models/custom_field.rb
- spec/models/custom_field_spec.rb
Better validations for List with an hash as `list_values`
> 6852 Update Customfields

- app/controllers/api/v1/internals/netex_imports_controller.rb
- app/controllers/api/v1/netex_imports_controller.rb
- config/routes.rb
- spec/controllers/api/v1/internals/netex_imports_controller_spec.rb
Reverts af83/chouette-core#627
> Revert "7231 Rationalize imports API"

- app/models/chouette/vehicle_journey.rb
- app/models/vehicle_journey_control/published_journey_name.rb
- app/models/vehicle_journey_control/purchase_window_dates.rb
- spec/models/compliance_controls/journey_pattern_controls/minimum_length_spec.rb
- spec/models/compliance_controls/vehicle_journey_control/published_journey_name_spec.rb
- spec/models/compliance_controls/vehicle_journey_control/purchase_window_dates_spec.rb
> Compliance controls specs

- app/controllers/subscriptions_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/subscription.rb
- app/models/user.rb
- app/views/devise/_links.html.slim
- app/views/devise/shared/_form_registration.html.slim
> 7368 - Set allow_unconfirmed_access_for = 1.day when Subscription.enabled?

- db/migrate/20180608082502_update_purchase_windows_colors.rb
> 7338 Migrate PurchaseWindow colors

- config/initializers/colorized_strings.rb
We don't want actual colors in production environment, as this would
only mess with the log files
> 7333 Adds a fallback for colorized strings

- Gemfile.lock
- app/models/chouette/routing_constraint_zone.rb
- app/models/chouette/stop_point.rb
- app/models/concerns/checksum_support.rb
- lib/tasks/referential.rake
- spec/models/chouette/routing_constraint_zone_spec.rb
- spec/models/route_spec.rb
Dépend de https://github.com/af83/has_array_of/pull/1
> 7526 fix rcz

- app/helpers/transport_mode_helper.rb
- config/locales/compliance_control_sets.en.yml
- config/locales/compliance_controls.en.yml
- config/locales/enumerize.en.yml
- config/locales/enumerize.fr.yml
Refs #6763
Refs #6839
Refs #6840
Add some new translations
> Refs #6837

- app/models/calendar_observer.rb
- config/application.rb
- spec/models/calendar_observer_spec.rb
Used here -> https://github.com/af83/chouette-its/pull/74
> Refs #7550 Enabling/Disabling of Calendar observer by config

- app/assets/stylesheets/_layout.sass
- app/assets/stylesheets/components/_on_off_switch.sass
- app/inputs/switchable_checkbox_input.rb
- app/views/lines/_form.html.slim
- config/locales/lines.en.yml
- config/locales/lines.fr.yml
> 7546 lines form

- app/models/merge.rb
- spec/models/merge_spec.rb
As well as corresponding referentials when new a merge is processed
> 7595 Delete outdated merges

- Gemfile
- Gemfile.lock
- app/workers/compliance_check_set_worker.rb
- app/workers/concerns/important_worker.rb
- app/workers/concerns/long_running_worker.rb
- app/workers/gtfs_import_worker.rb
- app/workers/line_referential_sync_worker.rb
- app/workers/merge_worker.rb
- app/workers/referential_cloning_worker.rb
- app/workers/simple_export_worker.rb
- app/workers/stop_area_referential_sync_worker.rb
- app/workers/workbench_import_worker.rb
- config/initializers/sidekiq.rb
- config/sidekiq.yml
And ensure that no job will block all the queues
> 7632 Use different queues for workers

- app/controllers/api/v1/internals/compliance_check_sets_controller.rb
- app/models/compliance_check_set.rb
- app/services/parent_notifier.rb
- app/workers/compliance_check_set_worker.rb
- spec/models/compliance_check_set_spec.rb
When a ControlSet is composed of both java and internal controls, ensure 
that the latter are actually called
> 7638 Fix "Mixed" ControlSets

- app/views/merges/show.html.slim
Show the rights controls on the merged referential
> 7675 Fix Merge#show

- app/inputs/full_time_zone_input.rb
- app/views/stop_areas/_form.html.slim
> 7007 - use select2 for country / timeZone inputs

- app/assets/stylesheets/components/_forms.sass
- app/helpers/application_helper.rb
- app/models/custom_field.rb
> 7636 Make attachments removable

- app/models/chouette/purchase_window.rb
- spec/models/chouette/purchase_window_spec.rb
> #6643 Use #max instead of #last in PurchaseWindows scopes

- app/models/referential_cloning.rb
Add a "g" flag in the sed command substituting the schema name
> 7683 Fix Referential Cloning

- app/assets/stylesheets/base/_config.sass
- app/assets/stylesheets/components/_merges.sass
- app/controllers/merges_controller.rb
- app/javascript/helpers/merge_referentials_selector.coffee
- app/views/merges/_form.html.slim
- config/locales/actions.en.yml
- config/locales/actions.fr.yml
Also, update the hidden input values when a referential is removed from 
the list
> 7691 New UX for Merge#new

- app/models/import/base.rb
- app/models/import/gtfs.rb
- spec/models/import/gtfs_spec.rb
And start by creating the Referential, as it is the more error-prone 
step
> 7655 & 6673 Add error messages when GTFS imports failed

- app/models/workbench.rb
- spec/models/merge_spec.rb
If it had been associated to a workbench
> 7708 Do not fail when a ComplianceControlSet is destroyed

- app/models/chouette/journey_pattern.rb
- lib/tasks/referential.rake
- spec/models/chouette/journey_pattern_spec.rb
⚠️ On n'oublie pas:
```
bundle exec rake referential:update_journey_patterns_checksums
```
> 7763 Update the JP#checksum when costs change

- app/models/merge.rb
- spec/models/merge_spec.rb
> 6622 Fix merge

- app/models/merge.rb
- spec/models/merge_spec.rb
Unless it is the first merge operation
> 7809 Prevent creation of new output in merge

- app/assets/javascripts/select2.coffee
- app/models/chouette/line.rb
- app/views/workbenches/_filters.html.slim
Truncate only on display but enable full text search for Lines in workbench index filter
> Refs #7629 Select2 truncation

- app/assets/javascripts/tables.coffee
- app/assets/stylesheets/components/_buttons.sass
- app/javascript/journey_patterns/components/JourneyPatterns.js
- app/javascript/vehicle_journeys/components/VehicleJourneys.js
> 7730 Fix popup menu

- lib/compliance_control_set_cloner.rb
- spec/lib/compliance_control_set_cloner_spec.rb
> 7893 Fix ComplianceControlSetCloner

- lib/tasks/ci.rake
```
$ bundle exec rake ci:add_temporary_security_check_ignore[CVE-2018-1000544]
$ bundle exec rake ci:check_security                                                                                                                                        system
Found vulnerability CVE-2018-1000544, ignored until 2018-09-27
bundle exec bundle-audit check --update --ignore CVE-2018-1000544
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
* branch            master     -> FETCH_HEAD
Current branch master is up to date.
Updated ruby-advisory-db
ruby-advisory-db: 321 advisories
No vulnerabilities found
```
> 7982 Add a mechanism to temporarily ignore vulnerabilities

- app/assets/stylesheets/_misc.sass
- app/assets/stylesheets/components/_lists.sass
- app/views/referential_lines/show.html.slim
- app/views/routes/show.html.slim
- config/locales/lines.en.yml
- config/locales/lines.fr.yml
> 6581 Fix Route#show

- app/models/chouette/journey_pattern.rb
- spec/models/chouette/journey_pattern_spec.rb
Add specs to ensure that JourneyPattern changes in stop_points are 
forwarded to the VehicleJourneys
> 8254 Add specs

- config/schedule.rb
- lib/tasks/cucumber.rake
> 8221 - Add rake task cucumber:clean_test_organisations

- app/models/chouette/stop_area.rb
- config/locales/stop_areas.en.yml
- config/locales/stop_areas.fr.yml
- spec/models/chouette/stop_area_spec.rb
Reverts af83/chouette-core#887. Refs #7784
> Revert "Refs #7784 Add validation to prevent stop area with parent to have a timezone"

- db/seeds/helpers/workgroups.rb
WHich is then used when sending the invitation email
> 8451 Add a optional locale in users seed

- spec/models/chouette/vehicle_journey_at_stop_spec.rb
- spec/models/chouette/vehicle_journey_at_stops_day_offset_spec.rb
- spec/models/chouette/vehicle_journey_spec.rb
Ensure VJAS times don't change according to winter/summer time
> 8508 Winter is coming

- app/models/concerns/custom_fields_support.rb
- app/models/custom_field.rb
- spec/models/chouette/vehicle_journey_spec.rb
when `ignore_empty_value_in_checksums`is set
> 8577 Ignore empty values in custom fields checksums

- app/models/chouette/route.rb
- app/workers/route_way_cost_worker.rb
- lib/tom_tom/delegator.rb
when the first try came back empty
> Refs #8538; Try again TomTom computation

- app/assets/stylesheets/mailers/components/h2.sass
- app/assets/stylesheets/mailers/components/h3.sass
- app/assets/stylesheets/mailers/components/mail_header.sass
- app/assets/stylesheets/mailers/components/tbody.sass
- app/assets/stylesheets/mailers/components/th.sass
- config/environments/production.rb.sample
And update production.rb.sample to use the mailer layout fot devise
> 9081; Fix font in mails

- app/policies/import_policy.rb
- app/views/referentials/show.html.slim
- spec/policies/import_policy_spec.rb
If the user is not allowed to see it
> 8612 Don't show link to import

- app/javascript/time_tables/components/PeriodForm.js
In the timetable period form, set year options depending on the modalProps begin year and last year.
> Refs #8873 In the timetable period form, set year options depending on the modalProps begin year and last year.

- app/models/import/gtfs.rb
- config/locales/import_messages.en.yml
- config/locales/import_messages.fr.yml
- lib/gtfs/time.rb
- spec/lib/gtfs/time_spec.rb
- Use better formatting in exports
- Make imports more flexibles
> 9271 Fix time formatting in GTFS

- app/services/referential_copy.rb
With non-sequential stop positions
> 9329 Fix aggregation bug

- app/services/referential_audit/full.rb
And skip inactive referentials
> 9277 Audit workgroup outputs

- app/javascript/helpers/cancel_button.js
- config/locales/en.yml
- config/locales/fr.yml
Quand l'utilisateur clique sur Annuler, on lui soumet la modale suivante :
>Avertissement
>
>Etes vous sûr de vouloir annuler l'action en cours ?
>
>Annuler | Ok
Il semble plus naturellement de proposer les choix :
> Non | Oui
> Refs #8987 better confirm action text

- app/assets/javascripts/transport_submode.coffee
- app/models/chouette/line.rb
- app/models/compliance_check_block.rb
- app/models/compliance_control_block.rb
- app/models/concerns/netex_transport_submode_enumerations.rb
- app/views/compliance_control_blocks/_form.html.slim
- app/views/lines/_form.html.slim
- config/locales/compliance_control_blocks.en.yml
- config/locales/compliance_control_blocks.fr.yml
- config/locales/lines.en.yml
- config/locales/lines.fr.yml
- spec/features/compliance_control_sets_spec.rb
- spec/lib/compliance_control_set_cloner_spec.rb
- spec/lib/compliance_control_set_copier_spec.rb
- spec/models/chouette/line_spec.rb
- spec/models/compliance_check_block_spec.rb
- spec/models/compliance_control_block_spec.rb
> Refs #9338 transport submode rules

- app/models/import/gtfs.rb
> 9495 - Don't call add_stop_point if import_stop_time returns nil in gtfs import

- app/assets/stylesheets/typography/_typography.sass
- app/helpers/merges_helper.rb
- app/helpers/operations_helper.rb
> 9870 Fix Merge icon color for disabled status

- app/views/referential_vehicle_journeys/_list.html.slim
Even if this case should not exist
> 9886 Protect VJs list

- app/models/calendar.rb
- app/models/chouette/time_table.rb
Between Timetables and PurchaseWindows
> 9888 Homogenize periods behaviour

- app/controllers/exports_controller.rb
- app/helpers/operations_helper.rb
- app/models/export/gtfs.rb
- app/views/exports/show.html.slim
- app/views/publications/show.html.slim
- config/breadcrumbs.rb
- config/locales/exports.en.yml
- config/locales/exports.fr.yml
- config/locales/publication_setups.en.yml
- config/locales/publication_setups.fr.yml
- config/routes.rb
> 9890 & 9887 Publications

- app/models/destination.rb
- app/models/destination/google_cloud_storage.rb
- app/models/destination/sftp.rb
Download files prior to sending them
> 9894 Fix destinations

- app/models/destination/google_cloud_storage.rb
Namely GoogleCloudStorage detinations
> 9892 Fix publications with empty exports

- app/views/compliance_check_sets/show.html.slim
- app/views/compliance_controls/show.html.slim
Fix l'erreur serveur obtenue quand on essaye de consulter un ComplianceControl qui appartient à un block "N arrets dans un pays"
> 9974 Fix ComplianceControl#show

- spec/models/compliance_controls/journey_pattern_controls/min_max_distance_cost_spec.rb
- spec/models/compliance_controls/journey_pattern_controls/minimum_length_spec.rb
- spec/models/compliance_controls/route_controls/border_count_spec.rb
- spec/models/compliance_controls/route_controls/stop_points_boarding_and_alighting_spec.rb
- spec/models/compliance_controls/route_controls/valid_stop_areas_spec.rb
Fix inconsistant context in specs
> 9987 Fix ComplianceControl specs

- app/models/compliance_check_block.rb
- app/models/compliance_controls/route_control/internal_base.rb
- app/models/compliance_controls/stop_area_control/time_zone.rb
- app/models/referential.rb
- config/locales/compliance_check_messages.en.yml
- config/locales/compliance_check_messages.fr.yml
- config/locales/compliance_controls.en.yml
- config/locales/compliance_controls.fr.yml
- spec/models/compliance_controls/stop_area_controls/timezone_spec.rb
Checks that all stopareas have a timezone set
> 9457 Add a StopAreaControl::Timezone

- app/helpers/menus_helper.rb
- app/views/layouts/navigation/_main_nav_left_content.html.slim
On a un problème quand il y a plusieurs Groupes de travail
> 9958 Allow all  panel items to have the same behaviour

- app/models/aggregate.rb
- app/models/workgroup.rb
- app/views/workgroup_outputs/show.html.slim
- config/locales/workgroups.en.yml
- config/locales/workgroups.fr.yml
- db/migrate/20190121081544_add_aggregated_at_to_workgroups.rb
- db/schema.rb
- spec/models/workgroup_spec.rb
A Rollback is considered like a new aggregation
> 9912 Store the last time a Workgroup offer was aggregated

- app/models/compliance_controls/custom_field_control/presence.rb
In CustomField::Presence control
> 9910 Fix VehicleJourneys collection URL

- app/controllers/referentials_controller.rb
- spec/controllers/referentials_controller_spec.rb
- spec/models/referential_spec.rb
Don't always trigger cloning from current offer
> 10587 Fix ReferentialsController

- spec/models/chouette/time_table_spec.rb
Acting weird on february whe, the next year is bisextile
> 10648 Fix Timetable spec

- app/javascript/vehicle_journeys/components/Tools.js
- app/javascript/vehicle_journeys/components/tools/CopyButton.js
- app/javascript/vehicle_journeys/components/tools/PasteButton.js
- app/javascript/vehicle_journeys/components/tools/SelectVehicleJourneys.js
- config/locales/actions.en.yml
- config/locales/actions.fr.yml
When copy/paste mode is enabled
Alse, add title on the copy & paste buttons
> 10654 In VJs editor, remove calendars button

- app/controllers/exports_controller.rb
Prevent error on form when it is submitted with errors
> 10696 Fix exports form

- app/services/referential_audit/base.rb
- app/services/referential_audit/journey_pattern_stop_points.rb
- app/services/referential_audit/vehicle_journey_at_stop_times.rb
Check that they have at least 2 stop_points
> 10492 Add audit on JourneyPatterns

- app/assets/stylesheets/components/_forms.sass
until they are moved to the top bar
> 8928 Hide form buttons

- app/models/import/gtfs.rb
- config/locales/import_messages.en.yml
- config/locales/import_messages.fr.yml
> 10561 - calendar.txt is not mandatory

- lib/stif/codif_line_synchronization.rb
- lib/stif/codifligne_line_id.rb
- lib/stif/dashboard.rb
- lib/stif/reflex_synchronization.rb
- lib/stif/workbench_scopes.rb
- spec/lib/stif/netex_file/frame_spec.rb
Reverts af83/chouette-core#1118
> Revert "8236 Remove subproject code"

- app/controllers/compliance_check_sets_controller.rb
- app/helpers/application_helper.rb
- app/helpers/compliance_check_sets_helper.rb
- app/helpers/imports_helper.rb
- app/policies/compliance_check_set_policy.rb
- app/policies/workbench_policy.rb
- spec/policies/compliance_check_set_policy_spec.rb
To see all ComplianceCheckSets
Also, check policies in the controller
> 10140 Grant permission to workgroups owners

- app/assets/stylesheets/application.sass
- app/assets/stylesheets/modules/devise.sass
- app/controllers/subscriptions_controller.rb
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/devise/shared/_form_registration.html.slim
- app/views/layouts/devise.html.slim
- app/views/layouts/navigation/_main_nav_top.html.slim
- app/views/layouts/navigation/_page_header.html.slim
- config/locales/devise.en.yml
- config/locales/devise.fr.yml
- config/routes.rb
- spec/views/lines/__snapshots__/lines/index.snap
- spec/views/lines/__snapshots__/lines/index_create.snap
- spec/views/lines/__snapshots__/lines/index_destroy.snap
- spec/views/lines/__snapshots__/lines/index_update.snap
- spec/views/lines/__snapshots__/lines/show.snap
- spec/views/lines/__snapshots__/lines/show_create.snap
- spec/views/lines/__snapshots__/lines/show_destroy.snap
- spec/views/lines/__snapshots__/lines/show_update.snap
> 10706 Split signin and signup in two distinct urls

- app/models/concerns/local_import_support.rb
- app/models/import/base.rb
- spec/models/import/gtfs_spec.rb
when we force an import failure
> 10740 Mark referential as failed

- app/controllers/import_messages_controller.rb
- app/controllers/imports_controller.rb
- app/helpers/application_helper.rb
- app/helpers/compliance_check_sets_helper.rb
- app/helpers/imports_helper.rb
- app/helpers/table_builder_helper.rb
- app/views/compliance_check_sets/index.html.slim
- app/views/compliance_check_sets/show.html.slim
- app/views/imports/import/_gtf.html.slim
- app/views/imports/import/_neptune.html.slim
- app/views/imports/import/_workbench.html.slim
- config/routes.rb
- show links only when the user can see the object
- show checks results
> 10584 Fix import show

- app/helpers/aggregates_helper.rb
- app/helpers/icon_helper.rb
- app/helpers/merges_helper.rb
- app/helpers/operations_helper.rb
- app/helpers/referentials_helper.rb
- app/models/concerns/operation_support.rb
- app/views/aggregates/show.html.slim
- app/views/referentials/show.html.slim
- app/views/workbench_outputs/show.html.slim
- app/views/workbenches/show.html.slim
- app/views/workgroup_outputs/show.html.slim
- config/locales/aggregates.en.yml
- config/locales/aggregates.fr.yml
- config/locales/merges.en.yml
- config/locales/merges.fr.yml
In Show and Indexes of referentials, merges and aggregations
> 10751 Flag urgent offer all along the workflow

- app/models/workgroup.rb
When trying to find out urgent offer
> 10778 Fix bug in aggregation

- app/controllers/merges_controller.rb
- app/helpers/aggregates_helper.rb
- app/helpers/merges_helper.rb
- app/helpers/referentials_helper.rb
- app/views/aggregates/_form.html.slim
- app/views/aggregates/show.html.slim
- app/views/merges/show.html.slim
- app/views/workbenches/show.html.slim
Stick it to the urgent referentials' name
> 10783 Move "urgent" flag

- app/controllers/referentials_controller.rb
- app/views/referentials/_form.html.slim
- config/routes.rb
- persist the "urgent" value if the form has an error
- fix the redirection on cancel
> 10660 Fix referentials form

- app/models/stop_area_routing_constraint.rb
- spec/models/chouette/vehicle_journey_spec.rb
- spec/models/stop_area_routing_constraint_spec.rb
when a linked stopareas constraint is updated
> 10781 Update vehilce journeys checksums

- app/policies/nightly_aggregate_policy.rb
Add missing NightlyAggregatePolicy
> 10822 Fix WorkgroupOutputsController#show

- app/jobs/long_running_job.rb
- app/models/concerns/local_import_support.rb
- config/application.rb
- config/initializers/delayed_job.rb
- spec/lib/delayed_job_spec.rb
- spec/models/import/gtfs_spec.rb
> 10866 Use custom job for long tasks

- app/views/layouts/navigation/_main_nav_top.html.slim
Show user actions even if organisation don't have change_locale feature. Refs #10911
> Fix main_nav_top

- .dockerignore
- .gitignore
- config/application.rb
- config/development_toolbar.rb
- config/environments/development.rb
- config/environments/production.rb.sample
Clean production.rb.sample in the same time
> 10950 Enable development toolbar with an ENV var

- app/views/devise/registrations/edit.html.slim
- config/locales/devise.en.yml
- config/locales/devise.fr.yml
@zog J'ai complètement enlevé le hint car étant donné que le user est déjà créé, et a accepté l'invitation, je ne sais pas si on peut savoir si l'utilisateur a déjà saisit un mot de passe ou non.
> Refs #10228 Display password hint if user has password set

- app/helpers/exports_helper.rb
- app/models/export/option_proxy.rb
> 11122 Fix Exports options

- app/controllers/exports_controller.rb
- app/controllers/publication_setups_controller.rb
- app/helpers/exports_helper.rb
- app/models/concerns/options_support.rb
- app/policies/publication_api_policy.rb
- app/policies/publication_setup_policy.rb
- app/views/publications/show.html.slim
- Fix collision of options names
- Fix bugs induced that the key used to store an option is no longer the 
attribute name
> 11160 Fix options support

- app/models/concerns/options_support.rb
- app/models/export/netex.rb
- app/models/publication_setup.rb
- spec/factories/publication_setups.rb
- spec/models/export/netex_spec.rb
Also, validate options set in PublicationApis
> 11185 Add min/max constraints on export options

- app/models/concerns/iev_interfaces/task.rb
- app/models/export/base.rb
- app/models/export/netex.rb
- app/models/publication.rb
- spec/models/publication_spec.rb
> 11180 Fix publication status computation

- app/views/publication_apis/show.html.slim
- config/locales/en.yml
- config/locales/fr.yml
- config/locales/publication_apis.fr.yml
Namely created_at and updated_at
> 11461 Add missing infos on PublicationApi#show

- app/controllers/routing_constraint_zones_controller.rb
- app/decorators/routing_constraint_zone_decorator.rb
- app/models/chouette/routing_constraint_zone.rb
- config/locales/routing_constraint_zones.en.yml
- config/locales/routing_constraint_zones.fr.yml
- spec/models/chouette/routing_constraint_zone_spec.rb
Given that all needed data are present
> 11103 Allow users to genrate Return RCZ

- app/models/chouette/objectid/stif_codifligne.rb
- app/models/chouette/objectid_formatter/stif_codifligne.rb
- spec/models/chouette/objectid/stif_codifligne_spec.rb
To accept new objectids formats
> 11683 Update Codifligne formatter

- app/services/workbench_import_service.rb
- app/services/zip_service.rb
- app/views/imports/import/_workbench.html.slim
- app/views/shared/iev_interfaces/_messages.html.slim
- spec/services/zip_service_spec.rb
Also, handle wrong dates formats
> 11757; Show errors messages when imports fails

- app/models/referential.rb
- spec/models/referential_spec.rb
As part of the referentials cleaning process
> 11783; Don't delete merged offers

- app/controllers/application_controller.rb
Force HTTPS urls for the XHR requests
> 11780; Fix routes form

- app/models/import/gtfs.rb
Fix unescaped quotes causing failures in PG
> 11802; Fix GTFS imports

- app/controllers/application_controller.rb
- app/views/routes/_form.html.slim
- app/views/routes/edit.html.slim
- app/views/routes/new.html.slim
This will prevent mixing HTTP end HTTPS urls
> 11780; Use relative URLs

- app/models/concerns/pretty_output.rb
- app/services/referential_audit/base.rb
- app/services/referential_audit/checksums.rb
- app/services/referential_audit/concerns/journey_pattern_base.rb
- app/services/referential_audit/concerns/vehicle_journey_base.rb
- app/services/referential_audit/full_referential.rb
- app/services/referential_audit/journey_pattern_distances.rb
- app/services/referential_audit/journey_pattern_stop_points.rb
- app/services/referential_audit/vehicle_journey_at_stop_times.rb
- app/services/referential_audit/vehicle_journey_initial_offset.rb
Add urls to faulty objects when relevant
> 10948 Make audits more verbose

- app/models/chouette/objectid_formatter/stif_codifligne.rb
> 11953; Fix lines search by ID

- app/javascript/vehicle_journeys/reducers/vehicleJourneys.js
- db/migrate/20190627094027_set_default_for_line_notice_ids.rb
- db/schema.rb
Occuring when trying to add a line_notice
> 11900; Fix VehicleJourney editions

- app/models/import/gtfs.rb
When one cannot import StopAreas
> 12006; Fix GTFS import

- app/models/chouette/route.rb
Which was causing failures during merge
> 11741; Fix routes cleaning

- app/models/chouette/vehicle_journey.rb
- spec/models/chouette/vehicle_journey_spec.rb
When line_notices are not enabled
> 11954; Fix VJ#update_has_and_belongs_to_many_from_state

- app/models/concerns/metadata_support.rb
- spec/models/route_spec.rb
When the object meta is incomplete
> 11871; Fix Metadata merge

- app/models/concerns/operation_support.rb
- app/models/referential.rb
- app/policies/clean_up_policy.rb
- app/views/referentials/show.html.slim
- spec/models/referential_spec.rb
Fix Referential#show when a Referential state is pending: show the 
actual operation keeping it on hold
> 12078 && 11506  Better Referential#show
