af83/chouette-core

app/models/clean_up.rb
spec/models/clean_up_spec.rb

Changes `CleanUp#clean`:
* Instead of destroying vehicle journeys outside the referential, destroy routes outside the referential. This will cascade deletion of vehicle journeys and journey patterns.
* Add a `methods` attribute for configuration which allows optional cleanups to be activated.
Notably, the `#destroy_{vehicle_journeys,journey_patterns,routes}` methods are no longer called by default because they're unnecessary work for referential duplication.
To re-enable them, the cleaner can be called as follows:
CleanUp.new(methods: [:destroy_empty]).clean

6854 clean up  destroy routes outside referential

---

app/assets/javascripts/modal_confirmation.js
app/decorators/compliance_control_decorator.rb
app/decorators/compliance_control_set_decorator.rb
app/decorators/line_decorator.rb
app/decorators/network_decorator.rb
app/decorators/purchase_window_decorator.rb
app/decorators/referential_line_decorator.rb
app/decorators/referential_network_decorator.rb
app/decorators/route_decorator.rb
app/decorators/routing_constraint_zone_decorator.rb
app/decorators/stop_area_decorator.rb
app/decorators/stop_area_referential_decorator.rb
app/javascript/vehicle_journeys/actions/index.js
app/views/lines/_form.html.slim
app/views/routing_constraint_zones/show.html.slim
config/breadcrumbs.rb
config/locales/actions.en.yml
config/locales/actions.fr.yml
config/locales/companies.en.yml
config/locales/layouts.en.yml
config/locales/layouts.fr.yml
config/locales/lines.en.yml
config/locales/networks.en.yml
config/locales/routing_constraint_zones.en.yml
config/locales/routing_constraint_zones.fr.yml
config/locales/stop_areas.en.yml
config/locales/time_tables.en.yml

J'ai juste remarqué que quand on switch de locale. Si on utilise un helper dans un decorator l'appli charge toujours l'I18n dans la 1ère locale
```ruby
...Switching from french to english
h.t(key) => toujours en française
t(key) => passe bien en anglais
```
Je ne sais pas à quoi c'est dû mais c'est là d'où viennent la plupart des soucis de traductions que soulève Cyrielle

Refs #6955 Add new translation + custom delete confirmation modal

---

Dockerfile

in order to cope with RMagick integration, the Docker image needs some extra libs

Install libmagickwand and friends

---

app/javascript/journey_patterns/actions/index.js
app/views/api/v1/journey_patterns/show.rabl

Fix a bug occuring if a route uses several times the same stops. In the
JourneyPattern Editor, you wouldn't be able to select the stop only once

7056 Fix JourneyPattern Editor

---

app/controllers/referentials_controller.rb
app/models/merge.rb
app/models/referential.rb
app/models/referential_metadata.rb
app/models/workbench.rb
app/models/workgroup.rb
app/views/referentials/_form.html.slim
lib/stif/workbench_scopes.rb
lib/workbench_scopes/all.rb
spec/models/referential/referential_oid_format_from_wkbch_spec.rb
spec/models/referential_metadata_spec.rb
spec/models/referential_spec.rb
spec/models/workbench_spec.rb

You can now define a `Workgroup.workbench_scopes_class` which will deal
with the association between a workbench and its lines and stops

6377 Make lines/stops associations with workbenches configurable

---

app/controllers/autocomplete_time_tables_controller.rb
spec/controllers/autocomplete_time_tables_controller_spec.rb

Juste pour info je crois que l'extension unaccent rajoute des colon ('-') à la place des whitespaces.
Là on a pas de soucies car on split les params à chaque whitespace mais ca peut surement poser soucis à un autre endroit.

Refs #7386 Fix autocomplete timetable split params

---

app/models/referential.rb
app/models/referential_cloning.rb

- run the cloning operation only once the transaction has been comitted 
(thus releasing previously aquired Locks)
- don't lock the DB to set the status of the Referential to `failed`

7535 attempt at solving deadlocks

---

config/environments/development.rb
config/environments/production.rb

```
$ bundle exec rake middleware
use Rack::Sendfile
use CacheSettings
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00007f9f17789ea8>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use DeviseCasAuthenticatable::SingleSignOut::StoreSessionId
run …
```

Refs #5986 reenable cache settings middleware

---

app/assets/stylesheets/_misc.sass
app/models/referential.rb
app/views/exports/_form.html.slim

- On ne charge que les référentiels pertinents
- On cache les champs "masqués" en CSS pour ne pas avoir de "flash" quand le JS passe

7811 Optimize export form

---

app/models/chouette/route.rb
app/models/chouette/routing_constraint_zone.rb
app/views/routing_constraint_zones/new.html.slim
config/locales/routing_constraint_zones.en.yml
config/locales/routing_constraint_zones.fr.yml

- Change RCZ Validation to force objects to have at least 2 stop points
- Only list routes with at least three stop points in the new form

Authorize editing RoutingConstrainZone with minimum 2 StopPoint  #7679 :

---

app/models/compliance_check_set.rb
spec/models/merge_spec.rb

Devrait fixer ce scénario: dans le cas d'un merge de 2 JDD, avec un JDC avant merge:
```
| Sidekiq                   | IEV                 |
|                           |                     |
|                           | lancement check #1  |
|                           | fin check #1        |
|                           | Notif fin check #1  |
| lancement check #1        | lancement check #2  |
| fin check #1              | fin check #2        |
| check #1 notif merge      | Notif fin check #2  | => A ce moment, en base, le check 2 est marqué comme "terminé" => on lance le merge :(
| lancement check #2        |                     |
| fin check #2              |                     |
| check #2 notif merge      |                     |
```

8420 Fix ComplianceCheckSet triggering merge too soon

---

app/models/chouette/objectid_formatter.rb
app/models/chouette/trident_active_record.rb
app/models/concerns/objectid_formatter_support.rb
app/models/concerns/objectid_support.rb
app/models/import/gtfs.rb
lib/af83/smart_cache.rb
spec/helpers/table_builder_helper_spec.rb
spec/models/chouette/objectid_formatter_spec.rb
spec/models/import/gtfs_spec.rb

- Use a reusable SmartCache lib
- We limit the cache size (save some memory for the others)

8205 Add cache to ObjectId formatters

---

app/views/stop_areas/show.html.slim

Actuellement dans la show des arrêts, on n'affiche pas l'adresse complète, on a seulement le code postal / ville / pays
-->  le champs "Nom de la rue" doit apparaître

Refs #8909 add street name to stop areas show view

---

app/models/referential.rb
spec/models/referential_spec.rb

On ne peut pas créer un JDD "2018 2019 Qqchose". Le formulaire revient (sans erreur explicite) parce que le slug généré par Chouette n'est pas valide.
Chouette génère un slug "qqchose" qui ne passe pas la validation du format de slug. Il faudrait que Referential#assignslug gère cette situation.

Refs #8446 fix referential slug format

---

app/models/clean_up.rb

Pass original referential state to the worker, to set it back afterward

10054 Fix CleanUp worker

---

app/javascript/vehicle_journeys/components/CopyModal.js

When `navigator.clipboard` is not defined

10550 Fix bug in Copy/Paste

---

app/models/concerns/local_import_support.rb
spec/lib/chouette/checksum_manager/transactional_spec.rb

Errors in import could lead to inconsistent checksums

10312 Fix GTFS import

---

INSTALL.md

On my system at least, had to install those libs before bundle install could succeed.

Added missing required libs for bundle install

---

app/models/concerns/objectid_support.rb

Fix the search with shortid when one uses the `ransack` method

10577 Fix search by shortid

---

app/models/import/base.rb
config/initializers/delayed_job.rb

When an import job is aborted, mark the resulting referentials as failed

10740 Fail pending referentials

---

app/models/application_model.rb
app/models/chouette/company.rb
app/models/chouette/journey_pattern.rb
app/models/chouette/objectid_formatter/base.rb
app/models/chouette/objectid_formatter/netex.rb
app/models/chouette/time_table.rb
app/models/concerns/checksum_support.rb
app/models/concerns/custom_fields_support.rb
app/models/concerns/iev_interfaces/resource.rb
app/models/concerns/iev_interfaces/task.rb
app/models/concerns/local_import_support.rb
app/models/concerns/objectid_support.rb
app/models/import/gtfs.rb
app/services/referential_audit/checksums.rb
db/schema.rb
lib/chouette/checksum_manager.rb
lib/chouette/checksum_manager/base.rb
lib/chouette/checksum_manager/no_updates.rb
spec/models/export/gtfs_spec.rb
spec/models/import/gtfs_spec.rb

You can now use `Import::Gtfs.profile(filepath, options)` in the console 
to easily run an import and get infos about where the time is spent

10866 Add a method to easily profile imports

---

config/locales/users.en.yml
config/locales/users.fr.yml

J'ai enlevé le paramètre user car on a pas (je crois de vraie page show pour un user).
En fait lors de la confirmation voici les params envoyés par le devise controller : 
```
{"confirmation_token"=>"_Vn7Cz-dAC1JCYMPmKmg",
"controller"=>"devise/confirmations",
"action"=>"show"}
```
Donc vu que l'action est show, par défaut on veut le param :user. 
Forcément enlever la clé c'est le plus simple.
Sinon à part ca voudrait dire renommer la route pour avoir une action custom de la part du devise controller ?

Refs #7808 Remove user parameter from i18n user key on show page

---

app/lib/cron.rb
app/lib/smart_env.rb
app/models/referential.rb
config/application.rb
config/environments/development.rb
config/initializers/cron.rb
spec/factories/merges.rb
spec/factories/referentials.rb
spec/models/referential_spec.rb

Automatically destroy old referentials once a day if the 
REFERENTIALS_CLEANING_COOLDOWN env variable is set up, with a value 
corresponding to the number of days the referentials must be retained

10376 Purge old referentials

---

app/models/stop_area_referential.rb

Locales were serialized twice, on app and db levels

12008; Fix StopAreaReferential

---

app/controllers/api/v1/internals/netex_imports_controller.rb
app/models/import/netex.rb

https://projects.af83.io/issues/12015
Juste un fix, car rails vérifiait le format des objetcid de lignes lors du pre-processing de l'import netex avant de faire appel à IEV. Il reste encore dans la partie rails beaucoup de référence à l'ancien format (STIF:CODIFLIGNE), mais mieux vaudrait faire un ticket spécifique pour celà.

12015 - New codifligne format regarding netex lines pre-parsing
